name: Test

on:
  push:

jobs:
  testgo:
    name: Test Go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true

      - name: Lint
        run: go vet ./...

      - name: Test
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57
